#! /bin/bash
files=("blankstatus" "btnCnt" "br_igmpProxy" "BtnMode" "gpio" "led" \
"push_button" "rtk_promiscuous" "rtk_vlan_support" "RstBtnCnt" "sw_nat" \
"reset_button_s" "drv_ctl" "ctrl" "data")
need_dir=(0 0 0 0 0 0 0 0 0 0 0 1 1 2 2)
file_dir=("NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" \
"NULL" "NULL" "simple_config" "quantum" "mii" "mii")
file_length=${#files[@]}
total=$[devices_length+file_length+1]
temp=0

for ((i=0;i<$file_length;i++))
do
    temp=$[(devices_length+i+1)*100/total]
    echo -e "\r$temp%\c"
    ./compile_file ${files[$i]} ${need_dir[$i]} ${file_dir[$i]}
done
echo -e "\r100%\c"
echo -e "\rbuild end!!"
echo "file in /file_ko"
