#! /bin/sh
if [ $# -ne 1 ];
then
	echo "Fail\nPlease input like: ./compile_newdev [device_name]"
else
	. ../../compile.config
	if [ `echo $kernel_version | cut -d '.' -f1` -eq 2 ]; then
		cp ../file/newdev_2.c newdev.c
	else
		cp ../file/newdev_3_4.c newdev.c
	fi
	cp ../file/Makefile .
	sed -e "s/firmadyne_newdev/$1/" -i newdev.c
	mv newdev.c $1.c
	sed -e "s/newdev/$1/" -i Makefile
	sed -e "s/arch/$_arch/" -i Makefile
	escape_root_dir=$(printf '%s\n' "$root_dir" | sed -e 's/[\/&]/\\&/g')
	sed -e "s/cross_compiler/$escape_root_dir\/toolchain\/$_arch_dir\/$header_version\/usr\/bin\/$cross_compiler/" -i Makefile
	make  >/dev/null 2>&1
	rm -rf *.symvers *.order *.o *.c Makefile .*.o.cmd .*.mod.o.cmd .*.ko.cmd .*.tmp .tmp_versions .*.mod.cmd >/dev/null 2>&1
	if [ ! -d ../md_ko/ ];
        then
		mkdir ../md_ko
	fi
	mv *.ko ../md_ko/
fi


